spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: Asia/Seoul

spring.profiles.active: local

server:
  port: 9000
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
#    url: jdbc:h2:~/test
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    initialize: true
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    database: h2
    show-sql: true
    open-in-view: true
  thymeleaf:
    mode: LEGACYHTML5

spring.thymeleaf.cache: false

book.api:
  url: https://apis.daum.net/v2
  auth: KakaoAK
  app-key: kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
  httpclient:
    pooling:
      maxTotal: 20
      maxPerRoute: 20
    connectionTimeout: 2000
    connectionRequestTimeout: 2000
    socketTimeout: 2500